Auto\MainBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        image:
            type: string
            length: 50
        is_active:
            type: boolean
        type:
            type: string
            length: 50
        date:
            type: datetime