Auto\MainBundle\Entity\BaseUser:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        name:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        region:
            type: string
            length: 255
        city:
            type: string
            length: 255