Auto\MainBundle\Entity\City:
    type: entity
    table: city
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        region_id:
            type: integer
            length: 15
        is_center:
            type: boolean