Auto\MainBundle\Entity\Comment:
    type: entity
    table: comments
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        id_auto:
            type: integer
            length: 11
        name:
            type: string
            length: 60
        email:
            type: string
            length: 60
        text:
            type: text
        date_add:
            type: datetime
        public:
            type: boolean
        parent_id:
            type: integer
            length: 11