Auto\MainBundle\Entity\Detail:
    type: entity
    table: detail
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        region:
            type: string
            length: 255
        mark:
            type: string
            length: 255
        model:
            type: string
            length: 255
        year:
            type: integer
            length: 4
        name:
            type: string
            length: 255
        vip:
            type: boolean
        img:
            type: string
            length: 255
            nullable: true
        price:
            type: decimal
            scale: 2
        description:
            type: text