parameters:
#    auto_admin.example.class: Auto\AdminBundle\Example

services:
#    auto_admin.example:
#        class: %auto_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
